# Generated by Django 4.2.3 on 2023-07-25 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_social_youtube_profile_social_github_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='short_intro',
            new_name='headline',
        ),
    ]
